- name: Copy mongo repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install the Mongodb
  ansible.builtin.dnf:
    name: mongodb-org
    state: installed

- name: Modify port to access by any server
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start MongoDB service
  ansible.builtin.systemd_service:
    name: mongod
    state: restarted
    enabled: yes












#printHeading " Modify port to access by any server using sed "
#sed -i -e 's/127.0.0.1/0.0.0.0/'  /etc/mongod.conf &>>$logFile
#statusCheck $?
#
#printHeading " Restart Application server "
#systemctl enable mongod &>>$logFile
#systemctl restart mongod &>>$logFile
#statusCheck $?
