- name: Roboshop APp Playbook # changed the names from frontend.yml to frontend_trail.yml, since Roles are created
  hosts: all
  become: yes
  tasks:
    - name: Disable Default Nginx
      ansible.builtin.shell:
        dnf module disable nginx -y

    - name: Enable nginx 24 version
      ansible.builtin.shell:
        dnf module enable nginx:1.24 -y

    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: Placing the nginx.conf
#      ansible.builtin.copy:  --> Copy just copy the files, so we change it to template to we can pass variables in the cmd line and use loops/conditions in templates
      ansible.builtin.template:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf

    - name : Start nginx
      ansible.builtin.systemd_service:
        name: nginx
        state: started


