- name: Front Playbook
  hosts: all
  become: yes
  tasks:
    - name: Disable Default Nginx
      ansible.builtin.shell:
        dnf module disable nginx -y

    - name: Enable nginx 24 version
      ansible.builtin.shell:
        dnf module enable nginx:1.24 -y

    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: Placing the nginx.conf
#      ansible.builtin.copy:  --> Copy just copy the files, so we change it to template to we can pass variables in the cmd line and use loops/conditions in templates
      ansible.builtin.template:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf

    - name : Start nginx
      ansible.builtin.systemd_service:
        name: nginx
        state: started


#
#  #echo -e "$color enable and start nginx $noColor"
#  #systemctl enable nginx
#  #systemctl start nginx
#  #statusCheck $?
#
#rm -rf /usr/share/nginx/html/*
#
#printHeading " Download the dev code and place it in tmp folder "
#curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
#statusCheck $?
#
#printHeading " Unzip the dev code from tmp folder "
#  # shellcheck disable=SC2164
#cd /usr/share/nginx/html
#unzip /tmp/frontend.zip
#statusCheck $?
#
#printHeading " Enable and Restart the nginx "
#systemctl enable nginx
#systemctl restart nginx
#statusCheck $?