- name: Copy Dispatch Service file
  ansible.builtin.template:
    src: dispatch.service
    dest: /etc/systemd/system/dispatch.service

- name: Install goLand
  ansible.builtin.dnf:
    name: golang
    state: installed

- name: Load app prerequisites
  ansible.builtin.include_role:
    name: common
    tasks_from: app_prerequisites

- name: Copy Download Application Dependencies
  ansible.builtin.shell: "{{ item }}"
  loop:
    - "go mod init dispatch"
    - "go get"
    - "go build"
  args:
    chdir: /app

- name: Load Systemd setup
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd_setup





