- name: Create a user 'roboshop' with a home directory
  ansible.builtin.user:
    name: roboshop


- name: Create application directory
  ansible.builtin.file:
    path: /app
    state: directory

- name:  Download the dev code and extract it
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ app_name }}-v3.zip
    dest: /app
    remote_src: yes

